language: node_js

services:
  - docker

before_install: 
  - echo minor > versionType.txt
  - echo Test > destination.txt
  - cat destination.txt
  - docker build . --tag="nwisweb_tableau_dockerinstance"
  - docker run --rm --name nwisweb_data_connector_docker nwisweb_tableau_dockerinstance

after_install:
  - cat ./coverage/lcov.info | coveralls
